### ISSUE TITLE
Question: how to compute job throughput

### ISSUE THREAD

**Issue by jasonallen** [elastic/esqueue#11]
I was wondering how I might be able to query the queue to determine what the throughput is (e.g. 1,812 jobs/hour). Unfortunately the only timestamp on a job document is the "created_at". A "completed_at" field would be great, but is there any other way I might be able to calculate that?

**Comment by w33ble** [comment]
There's not a way to query the queue directly, and there probably never will be. It's just not something we need.

Since it's all based on Elasticsearch though, you could do an aggregation of the count over time on the index you're using for the queue. The queue already adds `started_at` and `completed_at` fields to the documents as it works through them. You could probably also use pipeline aggs in Elasticsearch using that information to figure out how long jobs typically take to complete too.

Closing since this isn't an issue.
